import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useAuth } from '../../context/AuthContext';
import {
  ClipboardList, Plus, Search, Filter, Calendar, User,
  Briefcase, Clock, CheckSquare, X, Loader2, Check,
  ChevronDown, Tag, FileText, Trash2, TrendingUp, CheckCircle2,
  ExternalLink, Sparkles, AlertCircle, Layers, Download, Film
} from 'lucide-react';
import { db, sanitizeFirestorePayload } from '../../lib/firebase';
import {
  collection, query, where, getDocs, addDoc, setDoc, deleteDoc,
  doc, orderBy, onSnapshot, Timestamp
} from 'firebase/firestore';
import { DEFAULT_CLIENTS_MASTER, ensureCentralClientsSeeded } from '../../lib/clientMaster';
import { DEFAULT_EMPLOYEES_LIST } from './TasksView';
import { persistNewTask } from '../../lib/taskStorage';

// ─── Types ───────────────────────────────────────────────────────────
export interface WorkLog {
  id: string;
  employeeId: string;
  employee_id?: string;
  employeeName: string;
  employee_name?: string;
  clientId?: string;
  client_id?: string;
  clientName: string;
  client_name?: string;
  workDone: string;
  work_description?: string;
  category: string;
  task_type?: string;
  taskId?: string;
  task_id?: string;
  hours?: number;
  quantity?: number;
  workDetails?: string;
  work_details?: string;
  source?: 'task_completion' | 'manual' | string;
  auto_generated?: boolean;
  autoGenerated?: boolean;
  status?: string;
  date: string;
  work_date?: string;
  completedAt?: string;
  completed_at?: string;
  createdAt: string;
  created_at?: string;
  updatedAt?: string;
  updated_at?: string;
  task_reopened?: boolean;
  taskReopened?: boolean;
  video_production_id?: string;
  videoProductionId?: string;
}

const CATEGORIES = [
  'Graphic Design', 'Reel Editing', 'Video Shoot', 'Video Editing',
  'Script Writing', 'Caption Writing', 'Social Media', 'Meta Ads',
  'Google Ads', 'SEO', 'Website Update', 'Blog', 'Client Coordination',
  'Reporting', 'Photography', 'Other'
];

const inputCls = 'w-full bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] rounded-xl px-3.5 py-2.5 text-xs font-semibold text-[#101828] dark:text-[#F7F8FC] placeholder-[#7A8496] outline-none focus:border-[#5B4BFF] dark:focus:border-[#806CFF] transition-all';

export const normalizeWorkLog = (d: any, id: string): WorkLog => {
  const data = typeof d === 'object' && d ? d : {};
  const taskId = data.task_id || data.taskId || undefined;
  const clientId = data.client_id || data.clientId || '';
  const clientName = data.client_name || data.clientName || 'General Client';
  const employeeId = data.employee_id || data.employeeId || '';
  const employeeName = data.employee_name || data.employeeName || 'Team Member';
  const workDone = data.work_description || data.workDone || data.title || 'Completed deliverable';
  const category = data.task_type || data.category || 'General';
  const quantity = data.quantity !== undefined ? Number(data.quantity) : 1;
  const source = data.source || (taskId || data.auto_generated || data.autoGenerated ? 'task_completion' : 'manual');
  
  // Format date robustly (handles YYYY-MM-DD, ISO strings, and Firestore Timestamp)
  let dateStr = '';
  if (data.work_date && typeof data.work_date === 'string') {
    dateStr = data.work_date.slice(0, 10);
  } else if (data.date && typeof data.date === 'string') {
    dateStr = data.date.slice(0, 10);
  } else if (data.completed_at && typeof data.completed_at === 'string') {
    dateStr = data.completed_at.slice(0, 10);
  } else if (data.completedAt && typeof data.completedAt === 'string') {
    dateStr = data.completedAt.slice(0, 10);
  } else if (data.created_at && typeof data.created_at === 'string') {
    dateStr = data.created_at.slice(0, 10);
  } else if (data.createdAt && typeof data.createdAt === 'string') {
    dateStr = data.createdAt.slice(0, 10);
  } else if (data.work_date?.toDate) {
    dateStr = data.work_date.toDate().toISOString().slice(0, 10);
  } else if (data.date?.toDate) {
    dateStr = data.date.toDate().toISOString().slice(0, 10);
  } else {
    dateStr = new Date().toISOString().slice(0, 10);
  }

  return {
    id: id || data.id || `log_${Date.now()}`,
    taskId,
    task_id: taskId,
    clientId,
    client_id: clientId,
    clientName,
    client_name: clientName,
    employeeId,
    employee_id: employeeId,
    employeeName,
    employee_name: employeeName,
    workDone,
    work_description: workDone,
    category,
    task_type: category,
    hours: data.hours !== undefined ? Number(data.hours) : undefined,
    quantity,
    workDetails: data.work_details || data.workDetails || '',
    source,
    auto_generated: source === 'task_completion',
    autoGenerated: source === 'task_completion',
    status: data.status || 'completed',
    date: dateStr,
    work_date: dateStr,
    completedAt: data.completed_at || data.completedAt || new Date().toISOString(),
    completed_at: data.completed_at || data.completedAt || new Date().toISOString(),
    createdAt: data.created_at || data.createdAt || new Date().toISOString(),
    created_at: data.created_at || data.createdAt || new Date().toISOString(),
    updatedAt: data.updated_at || data.updatedAt || new Date().toISOString(),
    video_production_id: data.video_production_id || data.videoProductionId || data.videoTrackerId || undefined,
    videoProductionId: data.video_production_id || data.videoProductionId || data.videoTrackerId || undefined,
  };
};

// ─── Main Component ───────────────────────────────────────────────────
const getCachedWorkLogs = (): WorkLog[] => {
  if (typeof window === 'undefined') return [];
  try {
    const raw = localStorage.getItem('digi_persisted_worklogs_v2');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed.map((p, idx) => normalizeWorkLog(p, p.id || `cache_${idx}`));
    }
  } catch (e) {}
  return [];
};

export const WorkLogView: React.FC = () => {
  const { profile, user } = useAuth();
  const [logs, setLogs] = useState<WorkLog[]>(() => getCachedWorkLogs());
  const [tasks, setTasks] = useState<any[]>([]);
  const [clients, setClients] = useState<any[]>(DEFAULT_CLIENTS_MASTER);
  const [employees, setEmployees] = useState<any[]>(DEFAULT_EMPLOYEES_LIST);
  const [loading, setLoading] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [search, setSearch] = useState('');
  const [filterMonth, setFilterMonth] = useState(new Date().toISOString().slice(0, 7));
  const [filterEmployee, setFilterEmployee] = useState('');
  const [filterClient, setFilterClient] = useState('');
  const [activeTab, setActiveTab] = useState<'all' | 'tasks' | 'manual' | 'by-employee' | 'by-client'>('all');
  const [isRepairing, setIsRepairing] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const isAdmin = profile?.role === 'superAdmin' || profile?.role === 'admin';

  const triggerToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Load metadata and tasks with live updates
  useEffect(() => {
    ensureCentralClientsSeeded();

    const unsubClients = onSnapshot(collection(db, 'clients'), snap => {
      if (!snap.empty) {
        setClients(snap.docs.map(d => ({ id: d.id, clientId: d.id, ...d.data() })));
      } else {
        setClients(DEFAULT_CLIENTS_MASTER);
      }
    }, () => setClients(DEFAULT_CLIENTS_MASTER));

    const unsubEmployees = onSnapshot(collection(db, 'employees'), snap => {
      if (!snap.empty) {
        setEmployees(snap.docs.map(d => ({ id: d.id, ...d.data() })));
      } else {
        setEmployees(DEFAULT_EMPLOYEES_LIST);
      }
    }, () => setEmployees(DEFAULT_EMPLOYEES_LIST));

    const unsubTasks = onSnapshot(collection(db, 'tasks'), snap => {
      if (!snap.empty) {
        setTasks(snap.docs.map(d => ({ id: d.id, ...d.data() })));
      } else {
        try {
          const cachedTasksRaw = localStorage.getItem('digi_persisted_tasks_v2');
          if (cachedTasksRaw) setTasks(JSON.parse(cachedTasksRaw));
        } catch (e) {}
      }
    }, () => {
      try {
        const cachedTasksRaw = localStorage.getItem('digi_persisted_tasks_v2');
        if (cachedTasksRaw) setTasks(JSON.parse(cachedTasksRaw));
      } catch (e) {}
    });

    return () => {
      unsubClients();
      unsubEmployees();
      unsubTasks();
    };
  }, []);

  const [videos, setVideos] = useState<any[]>(() => {
    try {
      const raw = localStorage.getItem('digi_video_tracker_cache');
      return raw ? JSON.parse(raw) : [];
    } catch (e) {
      return [];
    }
  });

  // Real-time canonical logs listener with local cache sync & custom event listener
  useEffect(() => {
    const handleLogUpdate = (e: any) => {
      if (e?.detail) {
        const normalized = normalizeWorkLog(e.detail, e.detail.id || `evt_${Date.now()}`);
        setLogs(prev => {
          const filtered = prev.filter(l => l.id !== normalized.id && l.taskId !== normalized.taskId && l.task_id !== normalized.taskId);
          const next = [normalized, ...filtered];
          next.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
          return next;
        });
      }
    };
    window.addEventListener('worklogs_updated', handleLogUpdate);

    const unsubLogs = onSnapshot(collection(db, 'workLogs'), snap => {
      if (!snap.empty) {
        const list = snap.docs.map(d => normalizeWorkLog(d.data(), d.id));
        list.sort((a, b) => (b.date || '').localeCompare(a.date || ''));
        setLogs(list);
        try {
          localStorage.setItem('digi_persisted_worklogs_v2', JSON.stringify(list));
        } catch (e) {}
      } else {
        const cached = getCachedWorkLogs();
        if (cached.length > 0) setLogs(cached);
      }
      setLoading(false);
    }, (err) => {
      console.warn('WorkLogs listener notice (using cached logs):', err);
      const cached = getCachedWorkLogs();
      if (cached.length > 0) setLogs(cached);
      setLoading(false);
    });

    const unsubVideos = onSnapshot(collection(db, 'videoTracker'), snap => {
      if (!snap.empty) {
        const vList = snap.docs.map(d => ({ id: d.id, ...d.data() }));
        setVideos(vList);
      }
    }, () => {});

    return () => {
      window.removeEventListener('worklogs_updated', handleLogUpdate);
      unsubLogs();
      unsubVideos();
    };
  }, []);

  // Detect historical Done tasks & completed video production records without a linked Work Log
  const unsyncedDoneTasks = useMemo(() => {
    const missing: any[] = [];

    // 1. Check Tasks
    tasks.forEach(t => {
      const isDone = ['done', 'completed', 'approved'].includes((t.status || '').toLowerCase().trim());
      if (isDone) {
        const alreadyLogged = logs.some(l => l.taskId === t.id || l.task_id === t.id);
        if (!alreadyLogged) {
          missing.push({ type: 'task', data: t });
        }
      }
    });

    // 2. Check Video Tracker entries
    videos.forEach(v => {
      const shootDone = ['shot', 'editing', 'review', 'finished', 'Edited', 'Shot'].includes(v.status);
      const editDone = ['finished', 'Edited'].includes(v.status);
      const shootTaskId = v.shootTaskId || `task_shoot_${v.id}`;
      const editTaskId = v.editTaskId || `task_edit_${v.id}`;

      if (shootDone && !logs.some(l => l.taskId === shootTaskId || l.task_id === shootTaskId)) {
        missing.push({ type: 'video_shoot', data: v, shootTaskId });
      }
      if (editDone && !logs.some(l => l.taskId === editTaskId || l.task_id === editTaskId)) {
        missing.push({ type: 'video_edit', data: v, editTaskId });
      }
    });

    return missing;
  }, [tasks, videos, logs]);

  // Repair missing Work Logs for historical completed tasks and video records
  const handleRepairMissingLogs = async () => {
    if (unsyncedDoneTasks.length === 0) return;
    setIsRepairing(true);
    try {
      const { syncTaskCompletionToWorkLog } = await import('../../lib/taskWorkLogSync');
      const { syncVideoProductionToTasks } = await import('../../lib/productionBridge');
      let count = 0;

      for (const item of unsyncedDoneTasks) {
        if (item.type === 'task') {
          const t = item.data;
          await syncTaskCompletionToWorkLog(
            {
              taskId: t.id,
              title: t.title,
              description: t.description,
              clientId: t.clientId,
              clientName: t.clientName,
              assigneeId: t.assigneeId,
              assigneeName: t.assigneeName,
              category: t.category || 'Other',
              quantity: t.quantity || 1,
              videoProductionId: t.videoProductionId || t.videoTrackerId,
              video_production_id: t.videoProductionId || t.videoTrackerId,
            },
            profile,
            user?.uid
          );
          count++;
        } else if (item.type === 'video_shoot' || item.type === 'video_edit') {
          const v = item.data;
          await syncVideoProductionToTasks(v, { userProfile: profile, uid: user?.uid });
          count++;
        }
      }
      triggerToast(`✓ Successfully synced ${count} completed deliverable(s) to Work Log`);
    } catch (e) {
      console.error('Repair error:', e);
      triggerToast('Could not complete batch sync');
    } finally {
      setIsRepairing(false);
    }
  };

  const handleDelete = useCallback(async (logId: string) => {
    if (!window.confirm('Delete this work log record?')) return;
    try {
      await deleteDoc(doc(db, 'workLogs', logId));
      setLogs(prev => {
        const updated = prev.filter(l => l.id !== logId);
        try {
          localStorage.setItem('digi_persisted_worklogs_v2', JSON.stringify(updated));
        } catch (e) {}
        return updated;
      });
      triggerToast('Work log removed');
    } catch (e) {
      console.warn('Delete workLog notice:', e);
    }
  }, []);

  // Filter by search, client, employee, tab, & month
  const filtered = useMemo(() => {
    return logs.filter(l => {
      // 1. Month filter (if set)
      if (filterMonth && (!l.date || !l.date.startsWith(filterMonth))) {
        return false;
      }
      // 2. Tab filter
      if (activeTab === 'tasks') {
        if (l.source !== 'task_completion' && !l.taskId && !l.task_id) return false;
      }
      if (activeTab === 'manual') {
        if (l.source === 'task_completion' || !!l.taskId || !!l.task_id) return false;
      }
      // 3. Employee filter
      if (filterEmployee) {
        if (l.employeeId !== filterEmployee && l.employee_id !== filterEmployee && l.employeeName !== filterEmployee) {
          return false;
        }
      }
      // 4. Client filter
      if (filterClient) {
        if (l.clientId !== filterClient && l.client_id !== filterClient && l.clientName !== filterClient) {
          return false;
        }
      }
      // 5. Search text
      if (search) {
        const q = search.toLowerCase();
        const matchesWork = l.workDone?.toLowerCase().includes(q) || (l.work_description && l.work_description.toLowerCase().includes(q));
        const matchesClient = l.clientName?.toLowerCase().includes(q) || (l.client_name && l.client_name.toLowerCase().includes(q));
        const matchesEmp = l.employeeName?.toLowerCase().includes(q) || (l.employee_name && l.employee_name.toLowerCase().includes(q));
        const matchesCat = l.category?.toLowerCase().includes(q) || (l.task_type && l.task_type.toLowerCase().includes(q));
        if (!matchesWork && !matchesClient && !matchesEmp && !matchesCat) return false;
      }
      return true;
    });
  }, [logs, filterMonth, activeTab, filterEmployee, filterClient, search]);

  // Group by date
  const grouped: Record<string, WorkLog[]> = useMemo(() => {
    const res: Record<string, WorkLog[]> = {};
    filtered.forEach(l => {
      const d = l.date || 'Undated';
      if (!res[d]) res[d] = [];
      res[d].push(l);
    });
    return res;
  }, [filtered]);

  const sortedDates = useMemo(() => Object.keys(grouped).sort((a, b) => b.localeCompare(a)), [grouped]);

  // Summary stats (computed on current month or filtered set)
  const currentMonthLogs = useMemo(() => {
    return filterMonth ? logs.filter(l => l.date && l.date.startsWith(filterMonth)) : logs;
  }, [logs, filterMonth]);

  const totalHours = currentMonthLogs.reduce((sum, l) => sum + (l.hours || 0), 0);
  const taskLogsCount = currentMonthLogs.filter(l => l.source === 'task_completion' || !!l.taskId || !!l.task_id).length;
  const manualLogsCount = currentMonthLogs.filter(l => l.source !== 'task_completion' && !l.taskId && !l.task_id).length;
  const uniqueClients = new Set(currentMonthLogs.map(l => l.clientName || l.client_name)).size;

  // Export CSV
  const handleExportCSV = () => {
    const headers = ['Date', 'Client', 'Employee', 'Work Done', 'Category', 'Source', 'Hours/Qty'];
    const rows = filtered.map(l => [
      `"${l.date}"`,
      `"${l.clientName || l.client_name || ''}"`,
      `"${l.employeeName || l.employee_name || ''}"`,
      `"${l.workDone || l.work_description || ''}"`,
      `"${l.category || l.task_type || ''}"`,
      `"${l.source === 'task_completion' ? 'Task Completion' : 'Manual Entry'}"`,
      `"${l.hours ? l.hours + 'h' : l.quantity || 1}"`
    ]);
    const csv = 'data:text/csv;charset=utf-8,' + [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const encoded = encodeURI(csv);
    const link = document.createElement('a');
    link.setAttribute('href', encoded);
    link.setAttribute('download', `work_log_${filterMonth || 'all'}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-5 pb-12 font-sans">
      {/* ─── Toast Feedback ────────────────────────────────────────── */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-[#101828] dark:bg-[#161B31] text-white px-4 py-2.5 rounded-xl shadow-2xl border border-white/10 text-xs font-bold flex items-center gap-2 animate-in slide-in-from-bottom-5">
          <CheckCircle2 className="w-4 h-4 text-[#16A34A]" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* ─── Top Header ────────────────────────────────────────────── */}
      <div className="bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] rounded-2xl p-5 shadow-2xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-6 h-6 rounded-lg bg-[#EEECFF] dark:bg-[#201D45] text-[#5B4BFF] dark:text-[#806CFF] flex items-center justify-center">
              <ClipboardList className="w-3.5 h-3.5" />
            </div>
            <span className="text-[11px] font-black uppercase tracking-wider text-[#5B4BFF] dark:text-[#806CFF]">
              Agency Work Log & Reporting
            </span>
          </div>
          <h1 className="text-2xl font-black text-[#101828] dark:text-[#F7F8FC] tracking-tight">Work Done Log</h1>
          <p className="text-xs text-[#475467] dark:text-[#BAC1D1] mt-0.5">
            Single connected ledger for auto-synced completed deliverables and verified manual entries.
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleExportCSV}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold text-[#475467] dark:text-[#BAC1D1] bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] hover:bg-[#EEF1F6] dark:hover:bg-[#1C2439] transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" /> Export CSV
          </button>
          <button
            onClick={() => setShowForm(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wider text-white bg-[#5B4BFF] hover:bg-[#4E3FE6] dark:bg-[#806CFF] dark:hover:bg-[#725DEF] transition-all shadow-xs cursor-pointer"
          >
            <Plus className="w-4 h-4" /> Log Manual Work
          </button>
        </div>
      </div>

      {/* ─── Historical Sync Repair Banner ─────────────────────────── */}
      {isAdmin && unsyncedDoneTasks.length > 0 && (
        <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/60 rounded-2xl p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 shadow-2xs">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-amber-500/15 text-amber-600 dark:text-amber-400 flex items-center justify-center shrink-0">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <p className="text-xs font-bold text-amber-900 dark:text-amber-200">
                {unsyncedDoneTasks.length} Completed Deliverable{unsyncedDoneTasks.length > 1 ? 's' : ''} not yet in Work Log
              </p>
              <p className="text-[11px] text-amber-700 dark:text-amber-300/80">
                Sync historical completed tasks into the unified Work Done ledger idempotently.
              </p>
            </div>
          </div>
          <button
            onClick={handleRepairMissingLogs}
            disabled={isRepairing}
            className="flex items-center gap-1.5 px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white rounded-xl text-xs font-black uppercase tracking-wider transition-all shadow-xs cursor-pointer shrink-0 disabled:opacity-50"
          >
            {isRepairing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Sparkles className="w-3.5 h-3.5" />}
            Sync Missing Work Logs
          </button>
        </div>
      )}

      {/* ─── Stats KPI Row ────────────────────────────────────────── */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        {[
          { label: 'Total Logs', value: currentMonthLogs.length, sub: filterMonth || 'All Time', color: 'text-[#5B4BFF] dark:text-[#806CFF]', icon: Layers },
          { label: 'From Tasks', value: taskLogsCount, sub: 'Auto-synced', color: 'text-emerald-600 dark:text-emerald-400', icon: CheckCircle2 },
          { label: 'Manual Entries', value: manualLogsCount, sub: 'Ad-hoc work', color: 'text-[#2864FF] dark:text-[#4B85FF]', icon: FileText },
          { label: 'Hours Logged', value: `${totalHours}h`, sub: `${uniqueClients} clients`, color: 'text-amber-600 dark:text-amber-400', icon: Clock },
        ].map((s) => {
          const IconComp = s.icon;
          return (
            <div key={s.label} className="bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] rounded-2xl p-4 shadow-2xs flex items-center justify-between">
              <div>
                <p className="text-[10px] font-bold text-[#7A8496] dark:text-[#828BA1] uppercase tracking-wider">{s.label}</p>
                <p className={`text-2xl font-black ${s.color} mt-0.5 leading-none`}>{s.value}</p>
                <p className="text-[10px] text-[#7A8496] dark:text-[#828BA1] font-semibold mt-1">{s.sub}</p>
              </div>
              <div className="w-10 h-10 rounded-xl bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] flex items-center justify-center text-[#7A8496] shrink-0">
                <IconComp className="w-5 h-5" />
              </div>
            </div>
          );
        })}
      </div>

      {/* ─── Control Bar: Tab Switcher & Search/Filters ───────────── */}
      <div className="bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] rounded-2xl p-3 shadow-2xs space-y-3">
        <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-3">
          {/* Segmented View Tabs */}
          <div className="flex items-center bg-[#F7F8FC] dark:bg-[#171E31] p-1 rounded-xl border border-[#D7DEE9] dark:border-[#293248] overflow-x-auto">
            <button
              onClick={() => setActiveTab('all')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'all'
                  ? 'bg-white dark:bg-[#111728] text-[#101828] dark:text-[#F7F8FC] shadow-2xs border border-[#D7DEE9] dark:border-[#293248]'
                  : 'text-[#475467] dark:text-[#BAC1D1] hover:text-[#101828] dark:hover:text-white'
              }`}
            >
              All ({currentMonthLogs.length})
            </button>
            <button
              onClick={() => setActiveTab('tasks')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'tasks'
                  ? 'bg-emerald-600 text-white shadow-xs'
                  : 'text-[#475467] dark:text-[#BAC1D1] hover:text-[#101828] dark:hover:text-white'
              }`}
            >
              <CheckSquare className="w-3.5 h-3.5" />
              From Tasks ({taskLogsCount})
            </button>
            <button
              onClick={() => setActiveTab('manual')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'manual'
                  ? 'bg-[#5B4BFF] dark:bg-[#806CFF] text-white shadow-xs'
                  : 'text-[#475467] dark:text-[#BAC1D1] hover:text-[#101828] dark:hover:text-white'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              Manual ({manualLogsCount})
            </button>
          </div>

          {/* Month, Employee & Client filter */}
          <div className="flex flex-wrap items-center gap-2">
            <input
              type="month"
              value={filterMonth}
              onChange={e => setFilterMonth(e.target.value)}
              className="bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] rounded-xl px-3 py-1.5 text-xs font-bold text-[#101828] dark:text-[#F7F8FC] outline-none"
            />
            {isAdmin && (
              <select
                value={filterEmployee}
                onChange={e => setFilterEmployee(e.target.value)}
                className="bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] rounded-xl px-3 py-1.5 text-xs font-bold text-[#101828] dark:text-[#F7F8FC] outline-none cursor-pointer"
              >
                <option value="">All Employees</option>
                {employees.map(e => <option key={e.id} value={e.userId || e.id}>{e.name}</option>)}
              </select>
            )}
            <select
              value={filterClient}
              onChange={e => setFilterClient(e.target.value)}
              className="bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] rounded-xl px-3 py-1.5 text-xs font-bold text-[#101828] dark:text-[#F7F8FC] outline-none cursor-pointer"
            >
              <option value="">All Clients</option>
              {clients.map(c => <option key={c.id || c.clientId} value={c.id || c.clientId}>{c.clientName || c.name || c.businessName}</option>)}
            </select>
          </div>
        </div>

        {/* Search Toolbar */}
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-2 bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] rounded-xl px-3.5 py-2 flex-1">
            <Search className="w-4 h-4 text-[#7A8496] shrink-0" />
            <input
              type="text"
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search work logs by task, client, employee, category..."
              className="bg-transparent text-xs font-semibold text-[#101828] dark:text-[#F7F8FC] placeholder-[#7A8496] outline-none w-full"
            />
          </div>
          {(search || filterEmployee || filterClient) && (
            <button
              onClick={() => { setSearch(''); setFilterEmployee(''); setFilterClient(''); }}
              className="flex items-center gap-1 px-3 py-2 rounded-xl text-xs font-bold text-rose-600 border border-rose-200 bg-rose-50 hover:bg-rose-100 dark:bg-rose-950/30 dark:border-rose-800/40 transition-all cursor-pointer"
            >
              <X className="w-3.5 h-3.5" /> Clear
            </button>
          )}
        </div>
      </div>

      {/* ─── Log Entries Grouped by Date ───────────────────────────── */}
      {loading ? (
        <div className="space-y-3">
          {Array(4).fill(0).map((_, i) => (
            <div key={i} className="h-16 rounded-2xl bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] animate-pulse" />
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="flex flex-col items-center gap-3 py-12 text-center bg-white dark:bg-[#111728] border border-dashed border-[#D7DEE9] dark:border-[#293248] rounded-2xl shadow-2xs max-h-[160px] justify-center">
          <ClipboardList className="w-6 h-6 text-[#7A8496]" />
          <div>
            <p className="text-xs font-bold text-[#101828] dark:text-[#F7F8FC]">No work logs found for this filter</p>
            <p className="text-[11px] text-[#7A8496] dark:text-[#828BA1] mt-0.5">
              {activeTab === 'tasks'
                ? 'Complete tasks in Tasks & Work to automatically generate verified records.'
                : 'Log manual agency tasks or change your filters.'}
            </p>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {sortedDates.map(date => (
            <div key={date} className="space-y-2">
              <div className="flex items-center justify-between px-1">
                <p className="text-[11px] font-black uppercase tracking-wider text-[#7A8496] dark:text-[#828BA1]">
                  {new Date(date + 'T00:00:00').toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' })}
                </p>
                <span className="text-[10px] font-bold text-[#7A8496] dark:text-[#828BA1] bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] px-2 py-0.5 rounded-full shadow-2xs">
                  {grouped[date].length} {grouped[date].length === 1 ? 'entry' : 'entries'}
                </span>
              </div>

              <div className="bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] rounded-2xl shadow-2xs overflow-hidden divide-y divide-[#D7DEE9] dark:divide-[#293248]">
                {grouped[date].map((log, i) => (
                  <LogRow
                    key={log.id}
                    log={log}
                    last={i === grouped[date].length - 1}
                    isAdmin={isAdmin}
                    onDelete={() => handleDelete(log.id)}
                  />
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ─── Create Log Modal ──────────────────────────────────────── */}
      {showForm && (
        <CreateLogModal
          clients={clients}
          employees={employees}
          profile={profile}
          user={user}
          onClose={() => setShowForm(false)}
        />
      )}
    </div>
  );
};

// ─── LOG ROW ──────────────────────────────────────────────────────────
const LogRow: React.FC<{ log: WorkLog; last: boolean; isAdmin: boolean; onDelete: () => void }> = ({ log, last, isAdmin, onDelete }) => {
  const isAutoTask = log.source === 'task_completion' || !!log.taskId;

  return (
    <div className="flex items-center justify-between gap-3 px-4 py-3 hover:bg-[#F7F8FC] dark:hover:bg-[#171E31] transition-colors group">
      {/* Left: Source Icon & Title */}
      <div className="flex items-center gap-3.5 min-w-0 flex-1">
        <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 ${
          isAutoTask
            ? 'bg-emerald-50 text-emerald-600 border border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800/40'
            : 'bg-[#EEECFF] text-[#5B4BFF] border border-[#5B4BFF]/20 dark:bg-[#201D45] dark:text-[#806CFF] dark:border-[#806CFF]/30'
        }`}>
          {isAutoTask ? <CheckCircle2 className="w-4 h-4" /> : <FileText className="w-4 h-4" />}
        </div>

        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap">
            <p className="text-xs font-bold text-[#101828] dark:text-[#F7F8FC] truncate">{log.workDone}</p>
            
            {/* Source Badge */}
            {isAutoTask ? (
              <span className="inline-flex items-center gap-1 text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-700 border border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800/40">
                <Check className="w-2.5 h-2.5" /> Completed Task
              </span>
            ) : (
              <span className="inline-flex items-center gap-1 text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-[#EEECFF] text-[#5B4BFF] border border-[#5B4BFF]/20 dark:bg-[#201D45] dark:text-[#806CFF] dark:border-[#806CFF]/30">
                Manual Log
              </span>
            )}

            {(log.videoProductionId || log.video_production_id) && (
              <span className="inline-flex items-center gap-1 text-[9px] font-black uppercase tracking-wider px-2 py-0.5 rounded-md bg-purple-50 text-purple-700 border border-purple-200 dark:bg-purple-950/40 dark:text-purple-300 dark:border-purple-800/40">
                <Film className="w-2.5 h-2.5" /> Video Production
              </span>
            )}

            {log.reopenedCount && log.reopenedCount > 0 ? (
              <span className="text-[9px] font-bold px-1.5 py-0.2 rounded bg-amber-50 text-amber-700 border border-amber-200 dark:bg-amber-950/40 dark:text-amber-300">
                Reopened ({log.reopenedCount}x)
              </span>
            ) : null}
          </div>

          <div className="flex items-center gap-2.5 mt-1 text-[11px] text-[#7A8496] dark:text-[#828BA1] flex-wrap">
            {log.clientName && (
              <span className="font-semibold text-[#475467] dark:text-[#BAC1D1]">
                🏢 {log.clientName}
              </span>
            )}
            {log.category && (
              <span className="font-medium">
                · {log.category}
              </span>
            )}
            {log.employeeName && (
              <span className="font-medium">
                · 👤 {log.employeeName}
              </span>
            )}
            {log.taskId && (
              <span className="font-mono text-[9px] text-[#5B4BFF] dark:text-[#806CFF] bg-[#EEECFF] dark:bg-[#201D45] px-1.5 py-0.2 rounded">
                Ref: {log.taskId.substring(0, 10)}
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Right: Quantity / Hours & Actions */}
      <div className="flex items-center gap-3 shrink-0">
        {log.hours ? (
          <span className="text-[11px] font-bold text-amber-700 bg-amber-50 border border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800/40 px-2 py-0.5 rounded-lg flex items-center gap-1">
            <Clock className="w-3 h-3" /> {log.hours}h
          </span>
        ) : (
          <span className="text-[10px] font-bold text-[#7A8496] dark:text-[#828BA1] bg-[#F7F8FC] dark:bg-[#171E31] border border-[#D7DEE9] dark:border-[#293248] px-2 py-0.5 rounded-lg">
            Qty: {log.quantity || 1}
          </span>
        )}

        {isAdmin && (
          <button
            onClick={onDelete}
            title="Delete record"
            className="opacity-0 group-hover:opacity-100 p-1 rounded-lg text-[#7A8496] hover:text-rose-600 transition-all cursor-pointer"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        )}
      </div>
    </div>
  );
};

// ─── CREATE LOG MODAL ────────────────────────────────────────────────
const CreateLogModal: React.FC<{
  clients: any[];
  employees: any[];
  profile: any;
  user: any;
  onClose: () => void;
}> = ({ clients, employees, profile, user, onClose }) => {
  const [clientName, setClientName] = useState(clients[0]?.clientName || clients[0]?.name || '');
  const [employeeId, setEmployeeId] = useState(profile?.role === 'employee' ? (user?.uid || '') : (employees[0]?.userId || employees[0]?.id || user?.uid || ''));
  const [workDone, setWorkDone] = useState('');
  const [category, setCategory] = useState('Graphic Design');
  const [hours, setHours] = useState('');
  const [quantity, setQuantity] = useState('1');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [workDetails, setWorkDetails] = useState('');
  const [saving, setSaving] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const desc = workDone.trim();
    if (!desc) return;

    const qty = parseInt(quantity, 10);
    if (isNaN(qty) || qty < 1) return;

    setSaving(true);
    try {
      const selectedEmp = employees.find(e => (e.userId || e.id) === employeeId);
      const selectedClient = clients.find(c => (c.clientName || c.name || c.businessName) === clientName);

      const empId = employeeId || user?.uid || '';
      const empName = selectedEmp?.name || profile?.name || 'Team Member';
      const cId = selectedClient?.id || selectedClient?.clientId || '';
      const cName = clientName || selectedClient?.clientName || selectedClient?.name || 'General Client';
      const parsedHours = hours ? parseFloat(hours) : null;
      const nowIso = new Date().toISOString();
      const logId = `worklog_manual_${Date.now()}`;

      // Build pure Work Log payload (source: 'manual', taskId: null, NO phantom task created)
      const logWithId: any = {
        id: logId,
        workLogId: logId,
        task_id: null,
        taskId: null,
        client_id: cId,
        client_name: cName,
        clientId: cId,
        clientName: cName,
        employee_id: empId,
        employee_name: empName,
        employeeId: empId,
        employeeName: empName,
        work_description: desc,
        workDone: desc,
        description: desc,
        task_type: category,
        category,
        quantity: qty,
        hours: parsedHours ?? null,
        workDetails: workDetails.trim(),
        work_details: workDetails.trim(),
        work_date: date,
        workDate: date,
        date,
        completed_at: nowIso,
        completedAt: nowIso,
        created_at: nowIso,
        createdAt: nowIso,
        updated_at: nowIso,
        updatedAt: nowIso,
        source: 'manual',
        auto_generated: false,
        autoGenerated: false,
        status: 'completed',
      };

      const sanitized = sanitizeFirestorePayload(logWithId);

      // 1. Update local storage cache immediately
      try {
        const cached = getCachedWorkLogs();
        const updated = [logWithId, ...cached.filter((l: any) => l.id !== logId)];
        localStorage.setItem('digi_persisted_worklogs_v2', JSON.stringify(updated));
      } catch (e) {}

      // 2. Dispatch global events
      window.dispatchEvent(new CustomEvent('worklogs_updated', { detail: logWithId }));
      window.dispatchEvent(new Event('worklogs_updated'));

      // 3. Persist to Firestore
      try {
        await setDoc(doc(db, 'workLogs', logId), sanitized, { merge: true });
        await addDoc(collection(db, 'activityLogs'), {
          userId: user?.uid || '',
          userName: profile?.name || 'Team Member',
          action: `manually logged work: ${desc}`,
          details: `${cName} (${category})`,
          createdAt: nowIso,
        });
      } catch (firestoreErr) {
        console.warn('WorkLog Firestore write notice (cached locally):', firestoreErr);
      }

      onClose();
    } catch (err) {
      console.error('Save log error:', err);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in-50">
      <div className="bg-white dark:bg-[#111728] border border-[#D7DEE9] dark:border-[#293248] rounded-2xl p-6 max-w-lg w-full shadow-2xl space-y-4 animate-in zoom-in-95">
        <div className="flex items-center justify-between border-b border-[#D7DEE9] dark:border-[#293248] pb-3">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-[#EEECFF] dark:bg-[#201D45] text-[#5B4BFF] dark:text-[#806CFF] flex items-center justify-center">
              <Plus className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-black text-[#101828] dark:text-[#F7F8FC]">
                Log Manual Agency Work
              </h3>
              <p className="text-[11px] text-[#7A8496] dark:text-[#828BA1]">For work done outside scheduled board tasks</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg text-[#7A8496] hover:text-[#101828] dark:hover:text-white cursor-pointer">
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-3.5 text-xs">
          <div>
            <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
              Work Done / Deliverable Title *
            </label>
            <input
              type="text"
              required
              value={workDone}
              onChange={e => setWorkDone(e.target.value)}
              placeholder="e.g. Designed 3 Instagram story flyers for Monsoon Promo"
              className={inputCls}
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
                Client / Brand *
              </label>
              <select
                value={clientName}
                onChange={e => setClientName(e.target.value)}
                className={inputCls}
              >
                {clients.map(c => {
                  const name = c.clientName || c.name || c.businessName || 'Client';
                  return <option key={c.id || c.clientId} value={name}>{name}</option>;
                })}
              </select>
            </div>

            <div>
              <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
                Work Category
              </label>
              <select
                value={category}
                onChange={e => setCategory(e.target.value)}
                className={inputCls}
              >
                {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-2.5">
            <div>
              <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
                Date
              </label>
              <input
                type="date"
                required
                value={date}
                onChange={e => setDate(e.target.value)}
                className={inputCls}
              />
            </div>
            <div>
              <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
                Hours (Opt)
              </label>
              <input
                type="number"
                step="0.5"
                min="0"
                value={hours}
                onChange={e => setHours(e.target.value)}
                placeholder="e.g. 2.5"
                className={inputCls}
              />
            </div>
            <div>
              <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
                Quantity
              </label>
              <input
                type="number"
                min="1"
                value={quantity}
                onChange={e => setQuantity(e.target.value)}
                className={inputCls}
              />
            </div>
          </div>

          <div>
            <label className="block text-[11px] font-bold text-[#101828] dark:text-[#F7F8FC] mb-1">
              Deliverable Notes / Drive Link (Optional)
            </label>
            <textarea
              rows={2}
              value={workDetails}
              onChange={e => setWorkDetails(e.target.value)}
              placeholder="Paste Google Drive asset link, revisions, or proof notes..."
              className={inputCls}
            />
          </div>

          <div className="flex items-center justify-end gap-2 pt-2 border-t border-[#D7DEE9] dark:border-[#293248]">
            <button
              type="button"
              onClick={onClose}
              className="px-3.5 py-2 rounded-xl text-xs font-bold text-[#475467] dark:text-[#BAC1D1] hover:bg-[#EEF1F6] dark:hover:bg-[#171E31] cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 rounded-xl text-xs font-black uppercase tracking-wider text-white bg-[#5B4BFF] hover:bg-[#4E3FE6] dark:bg-[#806CFF] dark:hover:bg-[#725DEF] flex items-center gap-1.5 shadow-xs disabled:opacity-50 cursor-pointer"
            >
              {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Check className="w-3.5 h-3.5" />}
              <span>Save Work Log</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
