import { collection, query, where, getDocs, setDoc, updateDoc, doc, addDoc } from 'firebase/firestore';
import { db, sanitizeFirestorePayload } from './firebase';
import { ensureActiveFirebaseAuth } from './calendarStorage';

export interface TaskSyncData {
  taskId: string;
  title: string;
  description?: string;
  clientId?: string;
  clientName?: string;
  assigneeId?: string;
  assigneeName?: string;
  category?: string;
  completedAt?: string;
  dueDate?: string;
  quantity?: number;
  source?: string;
  videoProductionId?: string;
  video_production_id?: string;
}

export interface SyncResult {
  success: boolean;
  id?: string;
  action?: 'created' | 'updated';
  error?: string;
}

/**
 * Idempotently syncs a completed task into the Work Log collection.
 * Uses canonical schema supporting both snake_case and camelCase fields.
 * Uses deterministic document ID 'worklog_task_{taskId}' for absolute Firestore idempotency.
 */
export async function syncTaskCompletionToWorkLog(
  task: TaskSyncData,
  userProfile?: any,
  userId?: string
): Promise<SyncResult> {
  if (!task.taskId) return { success: false, error: 'Missing taskId' };
  
  await ensureActiveFirebaseAuth().catch(console.warn);

  const todayStr = new Date().toISOString().split('T')[0];
  const nowIso = new Date().toISOString();
  const completedDate = task.completedAt ? task.completedAt.slice(0, 10) : todayStr;
  const completedIso = task.completedAt || nowIso;
  const docId = `worklog_task_${task.taskId}`;
  const videoProdId = task.video_production_id || task.videoProductionId || null;

  const fallbackEmpId = task.assigneeId || userId || userProfile?.userId || userProfile?.uid || 'emp_unassigned';
  const fallbackEmpName = task.assigneeName || userProfile?.name || 'Team Member';

  const canonicalPayload = {
    id: docId,
    // Canonical snake_case schema fields
    task_id: task.taskId,
    client_id: task.clientId || '',
    client_name: task.clientName || 'Client',
    employee_id: fallbackEmpId,
    employee_name: fallbackEmpName,
    work_description: task.title,
    task_type: task.category || 'Task Delivery',
    quantity: task.quantity || 1,
    work_date: completedDate,
    completed_at: completedIso,
    created_at: nowIso,
    updated_at: nowIso,
    source: 'task_completion' as const,
    auto_generated: true,
    task_reopened: false,
    video_production_id: videoProdId,
    
    // CamelCase compatibility aliases
    taskId: task.taskId,
    clientId: task.clientId || '',
    clientName: task.clientName || 'Client',
    employeeId: fallbackEmpId,
    employeeName: fallbackEmpName,
    workDone: task.title,
    workDetails: task.description || '',
    category: task.category || 'Task Delivery',
    date: completedDate,
    completedAt: completedIso,
    createdAt: nowIso,
    updatedAt: nowIso,
    autoGenerated: true,
    status: 'completed',
    videoProductionId: videoProdId,
  };

  const sanitized = sanitizeFirestorePayload(canonicalPayload);

  // 1. Update local cache immediately
  try {
    const cachedLogsRaw = localStorage.getItem('digi_persisted_worklogs_v2');
    const cachedLogs = cachedLogsRaw ? JSON.parse(cachedLogsRaw) : [];
    const updatedLogs = [
      canonicalPayload,
      ...cachedLogs.filter((l: any) => l.taskId !== task.taskId && l.task_id !== task.taskId && l.id !== docId)
    ];
    localStorage.setItem('digi_persisted_worklogs_v2', JSON.stringify(updatedLogs));

    if (typeof window !== 'undefined') {
      window.dispatchEvent(new CustomEvent('worklogs_updated', { detail: canonicalPayload }));
    }
  } catch (e) {
    console.warn('Local workLog cache notice:', e);
  }

  // 2. Persist to Firestore with merge & auto-retry
  try {
    await setDoc(doc(db, 'workLogs', docId), sanitized, { merge: true });
  } catch (err: any) {
    console.warn('Retrying workLog setDoc with auth refresh:', err);
    try {
      await ensureActiveFirebaseAuth();
      await setDoc(doc(db, 'workLogs', docId), sanitized, { merge: true });
    } catch (retryErr) {
      console.warn('WorkLog Firestore retry notice (saved in cache):', retryErr);
    }
  }

  // 3. Write activity log
  try {
    await addDoc(collection(db, 'activityLogs'), {
      userId: userId || fallbackEmpId,
      userName: fallbackEmpName,
      action: `completed deliverable: "${task.title}" (Work Log synced)`,
      details: `Client: ${task.clientName || 'Direct'} · ID: ${task.taskId}${videoProdId ? ` · Video: ${videoProdId}` : ''}`,
      createdAt: nowIso,
    });
  } catch (e) {
    // Optional
  }

  return { success: true, id: docId, action: 'created' };
}

/**
 * Flags an existing Work Log if a task is moved out of Done back to In Progress / Review.
 */
export async function syncTaskReopenedState(taskId: string): Promise<void> {
  if (!taskId) return;
  const docId = `worklog_task_${taskId}`;
  const nowIso = new Date().toISOString();

  // 1. Update local cache
  try {
    const cachedLogsRaw = localStorage.getItem('digi_persisted_worklogs_v2');
    if (cachedLogsRaw) {
      const cachedLogs = JSON.parse(cachedLogsRaw);
      const updated = cachedLogs.map((l: any) => {
        if (l.taskId === taskId || l.task_id === taskId || l.id === docId) {
          return { ...l, taskReopened: true, task_reopened: true, reopenedAt: nowIso, lastReopenedAt: nowIso };
        }
        return l;
      });
      localStorage.setItem('digi_persisted_worklogs_v2', JSON.stringify(updated));
    }
  } catch (e) {}

  // 2. Update Firestore
  try {
    await updateDoc(doc(db, 'workLogs', docId), {
      taskReopened: true,
      task_reopened: true,
      reopenedAt: nowIso,
      lastReopenedAt: nowIso,
    });
  } catch (err) {
    // Also check for legacy doc IDs by query
    try {
      const snap = await getDocs(query(collection(db, 'workLogs'), where('taskId', '==', taskId)));
      if (!snap.empty) {
        await updateDoc(doc(db, 'workLogs', snap.docs[0].id), {
          taskReopened: true,
          task_reopened: true,
          reopenedAt: nowIso,
        });
      }
    } catch (e) {}
  }
}

